### ISSUE TITLE
Оружейка

### ISSUE THREAD

**Issue by Grandotten** [Harroway/SS13#14]
В оружейке не хватает баллистического оружия. Боевых патронов и оружия как такового вообще нет, а на пистолеты даже резиновых пуль не найти. Аблативная броня при нападении на станцию будет слишком эффективной.

**Comment by FireFlashie** [comment]
Вообще, это чистой воды маппинг. На Torch, как я помню, все это есть.
В ближайшее время мы перейдем на оный.
Если НЕ будет - добавим, как только оригинальный разрабы закончат работу над картой.
