### ISSUE TITLE
Не декоративная система навыков.

### ISSUE THREAD

**Issue by Hanter0718** [Harroway/SS13#18]
Запилить невозможность провести операцию/взаимодействовать с химдиспенсером/микроволновкой/духовкой/построить стену/разобрать стену/взломать дверь и прочее при низком уровне соответствующего навыка.
Вероятность успешного дизарма/попадания привязать к навыку рукопашки/стрельбы.
Соответственно чем моложе персонаж, тем меньше навыков можно взять, и никаких боевых ассистентов без квенты.
Было бы неплохо не давать зайти за главу при низком навыке командования, но не так важно как прочее.

**Comment by FireFlashie** [comment]
Было отказано, т.к. это потребует слишком огромной работы, а также слишком огромных вмешательств в билд.
Собственно, мы можем рассмотреть это потом, как у нас будет побольше разрабов.
Да и систему нужно для такого полностью переделывать.

**Comment by Hanter0718** [comment]
Не очень разбираюсь в вопросе, но что сложного в том, чтобы добавить при взаимодействии проверку на уровень навыка?
Конечно её нужно прописать не один и не два раза, но огромной работы не вижу не вижу, максимум на час-два, мне кажется. Где я не прав?
