### ISSUE TITLE
Имба шипы у повара

### ISSUE THREAD

**Issue by Lizzka** [Harroway/SS13#37]
# В чём проблема
Баг с тем, что резоми и слизнелюди могут быть ваншотнуты на шипах повара, не играет роли в какой они одежде, какие в них вещи - просто заменяет ваше персонажа куском мяса. Чем это плохо? Вред лору и банальной логике, потому что надевание на шипы не заставляет исчезнуть у вас костюм кэпа и его ID карту, а лору - потому что из воды не может получится мяса.
![image](https://cloud.githubusercontent.com/assets/22064488/19215255/7e383b6a-8da1-11e6-8a81-41acd68d091d.png)
P.S. Для того чтобы надеть кого-то на шипы, просто 1 раз нажмите граб и на шипы - это произойдёт мгновенно.
# Предложения её решения
Не должно давать надевать на шип представителей этих рас, или по крайне мере не должно давать надевать на шип живого и одетого персонажа. В случаи соблюдения этого - странным будет получение из воды мяса, потому тут либо не давать надеть слизнечеловека, либо же получать с этого какой-нибудь другой тип, я от себя могу сделать спрайты желе :D

**Comment by FireFlashie** [comment]
Отказано в фиксе.

**Comment by Lizzka** [comment]
Окончательное решение изменено.
Решение- сделать проверку по расам, в результате которой- персонажа убьёт, нанесёт урон, ничего не случится. Но сам вариант уничтожения персонажа по некоторым обстоятельствам был принят неправильным.
Просьба в случаи чего Хосту изъявить свой протест до 10 октября 15:00 по МСК, желательно.
