### ISSUE TITLE
Горшок мёртв

### ISSUE THREAD

**Issue by AdskyMent** [Harroway/SS13#6]
tldr
Я хорошо помню тот день, когда впервые взял в руки горшок с цветком. Я вышел с ним на улицу, и на меня стали странно коситься люди. В чем дело? 
Я понял, лишь найдя зеркало. Я стал растением.
Оказывается, во мне давно таилась суперспособность: я могу превращаться в горшки, когда беру их в руки. С большой силой приходит большая ответственность, и я хотел отдохнуть от неё в спусструшен, но когда я зашёл, меня ожидало нечто ужасное.
Горшки, всюду горшки. Люди берут их в руки и тоже становятся горшками! Я больше не уникален! Мою суперспособность изнасиловали грязным жестоким ботинком гтмрази! Я не могу с этим жить!

"Мееее, нифига, Дитрих пиздит, енто не баг." Нет, это баг. Даже если это задумывалось разработчиками как фича, вышло это крайне убого и отсосно.
Итак, почему это - баг? Человек со спрайтом растения перемещается со скоростью обычного человека. Бегающие горшки ломают атмосферу.
Даааалее
"Ну это шоб прятаться в них, ага". Нет. Помимо больших растений есть растения, которые визуально во много раз меньше человеческой тушки. Как только ты сможешь спрятаться в цветке на подоконнике, позвони мне (нет, не звони, роуминг). 
Ну, и вишенка на торте из кала - при экзамайне человека со спрайтом растения мы видим, что человек держит горшок в руках. А не является им.
Fin.

**Comment by AdskyMent** [comment]
5 часов гет.

**Comment by AdskyMent** [comment]
11 часов гет.

**Comment by FireFlashie** [comment]
Фича,  дальнейшее обсуждение закрыто.

**Comment by AdskyMent** [comment]
Не дотянули до рекорда, окей.
